name: Test and publish

on:
  ["push","pull_request"]

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - name: Cache Nuget
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install .Net 8
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'
    - name : Test
      run: |
        dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=lcov
        mv nccid.Test/TestResults/*/coverage.info lcov.info
    - name: Report coverage to Coveralls
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN }} 
        path-to-lcov: 'lcov.info'
    - name: Build
      run: ./build.sh
    - name: Upload binaries to release
      if: contains(github.ref, 'refs/tags/v')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ncc-win.zip
        asset_name: ncc-win.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Windows release zip"
