name: Test and publish

on:
  push

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name : coverlet
      run: dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=lcov
    - name: coveralls      
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN }} 
        path-to-lcov: 'nccid.Test/TestResults/*/coverage.info'
    - name: Build
      run: ./build.sh
    - name: Upload binaries to release
      if: contains(github.ref, 'refs/tags/v')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ncc-win.zip
        asset_name: ncc-win.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Windows release zip"
